json.id diet.id
json.day diet.day
json.weight diet.weight
json.nuts_and_seeds diet.nuts_and_seeds
json.greek_yogurt diet.greek_yogurt
json.cheese diet.cheese
json.almond_butter diet.almond_butter
json.zoodles diet.zoodles
json.spaghetti_squash diet.spaghetti_squash
json.hummus_and_guac diet.hummus_and_guac
json.cottage_cheese diet.cottage_cheese
json.fruit diet.fruit
json.happy diet.happy
json.bean diet.bean
json.chocolate_bar diet.chocolate_bar
